name: Buildah Action
inputs:
  fedora-version:
    description: 'Fedora version number for base image'
    required: true
  registry-password:
    description: 'A Github PAT'
    required: true
  image-registry:
    required: false
    default: ghcr.io/${{ github.repository_owner }}
  registry-user:
    required: false
    default: ${{ github.actor }}
  commit-sha:
    required: true
runs:
  using: "composite"
  steps:
  - name: 'Checkout fedora-vscodebox repo'
    uses: actions/checkout@v4
  - name: 'Build fedora-vscodebox image'
    id: build_image
    uses: redhat-actions/buildah-build@v2
    with:
      image: fedora-vscodebox
      tags: latest fedora-${{ inputs.fedora-version }} ${{ inputs.commit-sha }}
      containerfiles: |
        ./Containerfile
      build-args: |
        fedora_version=${{ inputs.fedora-version }}
  - name: Push image to GHCR
    uses: redhat-actions/push-to-registry@v2
    id: push
    with:
      image: ${{ steps.build_image.outputs.image }}
      tags: ${{ steps.build_image.outputs.tags }}
      registry: ${{ inputs.image-registry }}
      username: ${{ inputs.registry-user }}
      password: ${{ inputs.registry-password }}
      extra-args: |
        --disable-content-trust

  #- name: Echo outputs
  #  run: |
  #    echo "${{ toJSON(steps.push.outputs) }}"