name: Build Image using Containerfile
on:
  push:
    branches:
      - 'main' 
      - 'releases/**'
    paths:
      - 'Containerfile'
      - '.github/workflows/**'


jobs:
  build-latest:
    name: Build fedora:latest image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/build-container
      name: 'Build image with Buildah'
      with:
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        fedora-version: 'latest'
        commit-sha: ${{ github.sha }}

  build-43:
    name: Build fedora:43 image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/build-container
      name: 'Build image with Buildah'
      with:
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        fedora-version: '43'
        commit-sha: ${{ github.sha }}

  build-42:
    name: Build fedora:42 image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/build-container
      name: 'Build image with Buildah'
      with:
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        fedora-version: '42'
        commit-sha: ${{ github.sha }}